// Crie um programa que leia 2 números inteiros e 1 real. Calcule e mostre: o produto do primeiro
// com a metade do segundo, a soma do triplo do primeiro com o terceiro. O terceiro número
// digitado ao cubo.


import java.util.Scanner;
public class exer1{
     public static void main(String[] args) {

        int num ;
        Scanner scan = new Scanner (System.in);
        System.out.println("digite um numero : ");
        num=scan.nextInt();
        scan.close();

        int num2;
        Scanner scan2= new Scanner (System.in);
        System.out.println ("digite outro numero ");
        num2=scan.nextInt();
        scan.close();
        
    


         
    
}
}