#empresa umbrella

nome=(input("digite seu nome: "))
CPF=(input("digite seu CPF: "))
RG=(input("digite seu RG: "))
nascimento=(input("data de nascimento: "))
sexo=(input("digite seu sexo: "))
peso= float(input("digite seu peso: "))
tipo_sanguineo=(input("digite seu tipo sanguineo:"))
renda=float(input("digite sua renda: "))
endereco=(input("digite seu endereço: "))
telefone=(input("digite seu telefone: "))
cidade=(input("digite sua cidade: "))
estado=(input("digite seu estado: "))

print("\n----relatorio de cadastro do paciente----")
print("nome: {nome}")
print("CPF: {CPF}")
print("RG: {RG}")
print("data de nascimento: {nascimento}")
print("sexo: {sexo}")
print("peso: {peso}")
print("tipo sanguineo: {tipo_sanguineo}")
print("renda: {renda}")
print("endereço: {endereco}")
print("telefone: {telefone}")
print("cidade: {cidade} ")
print("estado: {estado}")
